site_name: Pokengine jCoad Documentation
site_url: https://sitename.example
theme:
  name: material
  
  font:
    text: Outfit
    code: Ubuntu Mono
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.footer
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips

  palette:
  # Dark Mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Dark Mode
    primary: black
    accent: orange

      # Light Mode
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Light Mode
    primary: white
    accent: orange

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - abbr
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://pokengine.org
    - icon: fontawesome/brands/discord
      link: https://discord.gg/XkGpwvE

nav:
  - Home: docs\index.md
  - Tilefuser:
    - Tilefuser: docs\Tilefuser\introductiontotilefuser.md
    - Creating a Tilemap: docs\Tilefuser\creatingatilemap.md
  - Mapbuilder:
    - Mapbuilder: docs\Mapbuilder\introductiontomapbuilder.md
    - Understanding Syntax: docs\Mapbuilder\understanding-syntax.md
    - Understanding Objects: docs\Mapbuilder\understanding-objects.md
    - Understanding Definitions: docs\Mapbuilder\understanding-objects.md
    - Understanding Data Types: docs\Mapbuilder\understanding-datatypes.md
  - Coding Reference:
    - Object Functions: docs\Coding Reference\object-functions.md
    - Entity Properties: docs\Coding Reference\entity-properties.md
    - Conditions: docs\Coding Reference\conditions.md
    - Triggers: docs\Coding Reference\triggers.md
    - Pokémon Generation: docs\Coding Reference\pokemon-generation.md
    - Battle Properties: docs\Coding Reference\battle-properties.md
  - Commonly Asked Questions:
    - Roles and Permissons: docs\Commonly Asked Questions\rolesandpermissions.md