site_name: Pokengine Documentation
site_url: https://pokengine-new.readthedocs.io
nav:
  - Home: index.md
  - Using This Guide:
      - Using This Guide: Using_This_Guide/understanding-guide.md
      - Objects: Using_This_Guide/understanding-objects.md
      - Definitions: Using_This_Guide/understanding-definitions.md
      - Variables: Using_This_Guide/understanding-variables.md
      - Data Types: Using_This_Guide/understanding-datatypes.md
      - About Mapbuilder: Using_This_Guide/what-is-mapbuilder.md
  - Utilities:
      - Root Objects: Utilities/root-objects.md
      - Tips & Tricks: Utilities/tips-and-tricks.md
      - Cheat Sheet: Utilities/cheat-sheet.md
  - Code Library:
      - Objects: Code_Library/objects.md
      - Entities: Code_Library/entities.md
      - Triggers: Code_Library/triggers.md
      - Conditions: Code_Library/conditions.md
      - Battle Properties: Code_Library/battle-properties.md
      - Pokemon Generation: Code_Library/pokemon-generation.md
  - How-To Guides:
      - Region TM Tutors: Feature_Guides/region-tm-tutors.md
      - Regional Weather Schedules: Feature_Guides/regional-weather-schedule.md
      - Trainer Battle AI: Feature_Guides/trainer-battle-ai.md
  - About:
      - Commonly Asked Questions: About/commonly-asked-questions.md
      - Roles and Permissions: About/rolesandpermissions.md
      - Request A Feature: About/request-a-feature.md

extra_css:
  - stylesheets/extra.css
theme:
  name: material

  font:
    text: Outfit
    code: Ubuntu Mono
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.footer
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - navigation.path
    - navigation.top
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate

  palette:
  # Dark Mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Dark Mode
    primary: black
    accent: orange

      # Light Mode
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Light Mode
    primary: white
    accent: orange

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - abbr
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://pokengine.org
    - icon: fontawesome/brands/discord
      link: https://discord.gg/XkGpwvE
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

